---
- name: Configure OpenSuse Tumbleweed
  hosts: localhost
  gather_facts: true
  become: true

  vars:
    package_list:
      - aisleriot
      - aisleriot-themes
      - code
      - elementary-xfce-icon-theme
      - ffmpeg-4
      - galculator
      - git
      - google-chrome-stable
      - htop
      - java-11-openjdk-devel
      - java-17-openjdk-devel
      - libavcodec56
      - libavcodec57
      - libavformat56
      - libavformat57
      - libavdevice56
      - libavdevice57
      - mate-themes
      - mc
      - nodejs18
      - pinta
      - remmina
      - steam
      - telegram-desktop
      - terraform
      - vlc
      - vokoscreenNG
      - xfce4-sensors-plugin
      - xfce4-systemload-plugin
      - xfce4-weather-plugin
       
  tasks:
  - name: Install Key for VSC
    ansible.builtin.rpm_key:
      state: present
      key: https://packages.microsoft.com/keys/microsoft.asc  
  
  - name: Install Packman Repository
    zypper_repository:
      name: Packman
      repo: 'http://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/'
      auto_import_keys: yes

  - name: Install Visual Studio Code Repository
    zypper_repository:
      name: Visual Studio Code
      repo: 'https://packages.microsoft.com/yumrepos/vscode'
      auto_import_keys: yes

  - name: Install Google Chrome Repository
    zypper_repository:
      name: Google Chrome
      repo: 'https://dl.google.com/linux/chrome/rpm/stable/x86_64'
      auto_import_keys: yes

  - name: Install packages
    zypper:
      name: "{{item}}"
      state: latest
    loop: "{{package_list}}"